apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: travelmemory
  labels:
    app: travelmemory
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: travelmemory
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
